#!/bin/bash

# MongoDB Atlas Migration Script for LuxyLyfe
# This script helps migrate from current Atlas to your Azure Atlas instance

echo "🚀 LuxyLyfe MongoDB Atlas Migration Guide"
echo "=========================================="
echo ""
echo "📋 Pre-Migration Checklist:"
echo "1. ✅ New MongoDB Atlas cluster created in Azure"
echo "2. ✅ Database user created with read/write permissions"  
echo "3. ✅ Network access configured (0.0.0.0/0 for development)"
echo "4. ✅ Connection string obtained from Atlas dashboard"
echo ""
echo "🔄 Migration Steps:"
echo ""
echo "Step 1: Backup Current Data"
echo "  npm run backup-data"
echo ""
echo "Step 2: Update Connection String"
echo "  Update DATABASE_URL in .env.local with your Azure Atlas connection"
echo ""
echo "Step 3: Initialize New Database"
echo "  npx prisma generate"
echo "  npx prisma db push"
echo ""
echo "Step 4: Seed Initial Data"
echo "  npm run prisma:seed"
echo "  node seed-footer-content.js"
echo ""
echo "Step 5: Test Connection"
echo "  node test-azure-mongodb-connection.js"
echo ""
echo "Step 6: Start Application"
echo "  npm run dev"
echo ""
echo "🔐 Your new DATABASE_URL should look like:"
echo "mongodb+srv://USERNAME:PASSWORD@CLUSTER.xxxxx.mongodb.net/luxylyfe_db?retryWrites=true&w=majority"
echo ""
echo "💡 Tips:"
echo "- Keep your old connection as backup until migration is complete"
echo "- Test thoroughly in development before deploying to production"
echo "- Monitor Atlas dashboard for connection and performance metrics"
